apiVersion: batch/v1
kind: CronJob
metadata:
  name: skyscraper-cloud-sync
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:

      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "skyscraper-server.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.skyscraper_server.podSecurityContext | nindent 12 }}
          containers:
            - name: skyscraper-cloud-sync
              image: "{{ .Values.skyscraper_server.image.name }}"
              imagePullPolicy: {{ .Values.skyscraper_server.image.pullPolicy }}
              command:
                - /usr/local/bin/skyscraper-server
                - cloud-sync
              {{- if .Values.skyscraper_server.config.enabled }}
              volumeMounts:
                - mountPath: /app/config.yaml
                  name: skyscraper-server-config
                  subPath: config.yaml
              {{- end }}
              resources:
                {{- toYaml .Values.skyscraper_server.resources | nindent 16 }}
          {{- with .Values.skyscraper_server.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.skyscraper_server.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.skyscraper_server.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: OnFailure
          volumes:
            {{- if .Values.skyscraper_server.config.enabled }}
            - name: skyscraper-server-config
              configMap:
                name: {{ .Values.skyscraper_server.config.configMapName }}
                items:
                  - key: {{ .Values.skyscraper_server.config.environmentPath }}
                    path: config.yaml
            {{- end }}
