{{- if .Values.skyscraper_web.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skyscraper-web.serviceAccountName" . }}
  labels:
    {{- include "skyscraper-web.labels" . | nindent 4 }}
  {{- with .Values.skyscraper_web.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.skyscraper_server.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skyscraper-server.serviceAccountName" . }}
  labels:
    {{- include "skyscraper-server.labels" . | nindent 4 }}
  {{- with .Values.skyscraper_server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
